# Generated by Django 3.1.1 on 2021-09-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidPrediction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
