# Generated by Django 3.1.1 on 2021-10-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidPrediction', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='user_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
