# Generated by Django 3.1.1 on 2021-10-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidPrediction', '0003_patients_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
